services:

  postgresql:
    image: postgres:latest
    container_name: tadil-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tadil
      POSTGRES_PASSWORD: Tadil!
    volumes:
      - tadil_postgres_volume:/var/lib/postgresql

  minio:
    image: quay.io/minio/minio:latest
    container_name: tadil-minio
    restart: unless-stopped
    command: minio server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: tadil
      MINIO_ROOT_PASSWORD: TadilMinio!
    volumes:
      - tadil_minio_volume:/data
    ports:
      - 9002:9000
      - 9003:9001

volumes:
  tadil_postgres_volume:
  tadil_minio_volume:
